"""
Django settings for facultyWebsite project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd1234asdafsdf1324qwrgqergjan12341234go-inseasdfkljqhowiueq94038029384752093452039457curalsdkfjanlsdfe-b-*(ggfs+e=98&hqf+14z1mql2-im1mf#ksjdhgkjdshfkjdshfgkjashgdfkjaghadfkhgsdaskjdfa83-09v81#h^vjd99'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


LOCALE_PATHS = [
    os.path.join(BASE_DIR,'locale/')
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'index',
    'ckeditor',
    'ckeditor_uploader',
    'phonenumber_field',
    'rosetta',
    'parler',
]


CKEDITOR_UPLOAD_PATH = os.path.join(BASE_DIR,'static/images/ckeditor/uploads/')

CKEDITOR_CONFIGS = {
    'default':{
        'toolbar':'Custom',
    },
    'special':{
        'toolbar':'Special',
        'toolbar_Special':[['font-family'],],
        'extraPlugins':'font-family'
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'facultyWebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'facultyWebsite.extra_context.context'
            ],
        },
    },
]

WSGI_APPLICATION = 'facultyWebsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


PARLER_LANGUAGES = {
    1: (
        {'code': 'uz',},
        {'code': 'ru',},
        {'code': 'en',},
    ),
    'default': {
        'fallback': 'uz',             # defaults to PARLER_DEFAULT_LANGUAGE_CODE
        'hide_untranslated': False,   # the default; let .active_translations()       return fallbacks too.
    }
}

SITE_ID = 1


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'uz-Uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
MEDIA_URL = '/images/' 
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/images/')
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'statics/')
STATICFILES_DIRS=[
	os.path.join(BASE_DIR, 'static/')
]

from django.utils.translation import gettext_lazy as _

LANGUAGES = (
    ('uz',('Uzbek')),
    ('ru',('Russian')),
    ('en',('English')),
    
)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'navbarnavbar@gmail.com'
EMAIL_HOST_PASSWORD = 'Smartphoneslaptops'


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#Parler configuration
PARLER_DEFAULT_LANGUAGE_CODE = 'uz'
