# Generated by Django 4.0.2 on 2022-05-24 17:14

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Tekst kategoriyalari ',
                'verbose_name_plural': 'Tekst kategoriyalari ',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationTitle', models.CharField(choices=[('Stajor_oqituvchi', "Stajor 'oqituvchi"), ('oqituvchi', "O'qituvchi"), ('katta_oqituvchi', "Katta o'qituvchi"), ('dotsent', 'Dotsent'), ('professor', 'Professor'), ('akademik', 'Akademik')], max_length=50, verbose_name="O'qitish Mansabi")),
                ('birthdate', models.DateField(verbose_name='Tugilgan yili')),
                ('passportSeries', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(code='invalid_passportSeries', message='Notogri passport seriyasi', regex='[a-zA-Z]')], verbose_name='Passport seriyasi')),
                ('passportNumber', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_passportNumber', message='Notogri passport nomer', regex='[0-9]{7}')])),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('dateOfEntry', models.DateField(verbose_name='Ish boshlagan vaqti')),
                ('image', models.ImageField(upload_to='', verbose_name='Rasmi')),
            ],
            options={
                'verbose_name': 'Xodimlar ',
                'verbose_name_plural': 'Xodimlar ',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IndexCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Slayd Rasmi')),
            ],
            options={
                'verbose_name': 'Slaydlar ',
                'verbose_name_plural': 'Slaydlar ',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MainInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefon raqam')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegramga havola')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagramga link')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook ga link')),
                ('youtube', models.URLField(blank=True, verbose_name='Facebook ga link')),
                ('map_url', models.URLField(verbose_name='Google yoki yandex xaritaga link')),
            ],
            options={
                'verbose_name': 'Asosiy malumotlar ',
                'verbose_name_plural': 'Asosiy malumotlar ',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', "Tanlo'v yangiliklari"), ('2', 'Talim yangiliklari')], max_length=50, verbose_name='Kategoriyasi')),
                ('image', models.ImageField(upload_to='', verbose_name='Rasm')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Yangiliklar ',
                'verbose_name_plural': 'Yangiliklar ',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReceptionTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField(verbose_name='Qabul qilish boshlanish vaqti')),
                ('endTime', models.TimeField(verbose_name='Qabul qilish tugash vaqti')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.employees', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Qabul qiluvchi odamlar ',
                'verbose_name_plural': 'Qabul qiluvchi odamlar ',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Resurs kategoriyalari ',
                'verbose_name_plural': 'Resurs kategoriyalari  ',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('image', models.ImageField(upload_to='', verbose_name='Rasm')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.resourcecategory', verbose_name='Resurs kategoriyasi')),
            ],
            options={
                'verbose_name': 'Resurslar ',
                'verbose_name_plural': 'Resurslar ',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TalentedStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(verbose_name="Tug'ilgan kuni")),
                ('img', models.ImageField(upload_to='', verbose_name='Rasm')),
                ('isInHome', models.BooleanField(verbose_name='Bosh sahifada tursinmi')),
            ],
            options={
                'verbose_name': 'Talantli fakultet yulduzlar',
                'verbose_name_plural': 'Talantli fakultet yulduzlar ',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.categorytexts')),
            ],
            options={
                'verbose_name': 'Tekstlar',
                'verbose_name_plural': 'Tekstlar',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TextsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Tekst')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='index.texts')),
            ],
            options={
                'verbose_name': 'Tekstlar Translation',
                'db_table': 'index_texts_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TalentedStudentsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('fullname', models.CharField(max_length=100, verbose_name="To'liq ismi")),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(verbose_name="To'liq tavsif")),
                ('title', models.CharField(max_length=100, verbose_name='Ilmiy unvoni')),
                ('specialization', models.CharField(max_length=100, verbose_name='Mutaxasisligi')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='index.talentedstudents')),
            ],
            options={
                'verbose_name': 'Talantli fakultet yulduzlar Translation',
                'db_table': 'index_talentedstudents_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ResourcesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Qonun sarlavhasi')),
                ('short_description', models.TextField(max_length=200, verbose_name='Qonun qisqa tavsifi')),
                ('file', models.FileField(upload_to='', verbose_name='Fayl')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='index.resources')),
            ],
            options={
                'verbose_name': 'Resurslar  Translation',
                'db_table': 'index_resources_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ResourceCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='index.resourcecategory')),
            ],
            options={
                'verbose_name': 'Resurs kategoriyalari  Translation',
                'db_table': 'index_resourcecategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReceptionTimesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('room', models.CharField(max_length=15, verbose_name='Xona raqami')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='index.receptiontimes')),
            ],
            options={
                'verbose_name': 'Qabul qiluvchi odamlar  Translation',
                'db_table': 'index_receptiontimes_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NewsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Yangilik sarlavhasi')),
                ('short_description', models.CharField(max_length=200, verbose_name='Yangilik qisqa tavsifi')),
                ('full_desc', ckeditor_uploader.fields.RichTextUploadingField(verbose_name="To'liq tavsif")),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='index.news')),
            ],
            options={
                'verbose_name': 'Yangiliklar  Translation',
                'db_table': 'index_news_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MainInfosTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('address', models.CharField(max_length=200, verbose_name='Manzil')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='index.maininfos')),
            ],
            options={
                'verbose_name': 'Asosiy malumotlar  Translation',
                'db_table': 'index_maininfos_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IndexCarouselTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavhasi')),
                ('text', models.CharField(max_length=10000000, verbose_name='Slayd matni')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='index.indexcarousel')),
            ],
            options={
                'verbose_name': 'Slaydlar  Translation',
                'db_table': 'index_indexcarousel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EmployeesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='FIO')),
                ('position', models.CharField(max_length=200, verbose_name='Mansabi')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='index.employees')),
            ],
            options={
                'verbose_name': 'Xodimlar  Translation',
                'db_table': 'index_employees_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryTextsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='index.categorytexts')),
            ],
            options={
                'verbose_name': 'Tekst kategoriyalari  Translation',
                'db_table': 'index_categorytexts_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
